# Generated by Django 4.2.4 on 2023-08-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initialize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discription',
            name='disc',
            field=models.TextField(),
        ),
    ]
